name: 'Configure Deployment Environment'
description: 'Set and export environment variables needed to deploy to AWS based on branch name'
inputs:
  branch:
    description: 'name of the branch, pass in GITHUB_REF'
    required: true
  application:
    description: 'application this repo belongs to for finidng the namespace to deploy to'
    required: true
  variables:
    description: 'Vars as JSON'
    required: true    
  secrets:
    description: 'secrets as JSON'
    required: true      
runs:
  using: "composite"
  steps:
    - name: Get Environmnet From Branch
      shell: bash
      run: |
        echo "BRANCH=$(echo ${{ inputs.branch }} | cut -d'/' -f 3)"
        BRANCH=$(echo ${{ inputs.branch }} | cut -d'/' -f 3)
        if [[ ${BRANCH,,} == 'master' || ${BRANCH,,} == 'main' ]]; then
            echo "AWS_ENV=PROD" >> $GITHUB_ENV
        elif [[ ${BRANCH,,} == 'development' || ${BRANCH,,} == 'develop' ]]; then
            echo "AWS_ENV=DEV" >> $GITHUB_ENV
        else
            echo "AWS_ENV=FEATURE" >> $GITHUB_ENV
        fi      

    - name: check env context
      shell: bash
      env:
        VARIABLES: ${{ inputs.variables }}  
        APPLICATION: ${{ inputs.APPLICATION }}
      run: |
        echo "variables:"
        echo "$VARIABLES"
        echo "APPLICATION_NAME=$(echo ${APPLICATION@U})" >> "$GITHUB_ENV"
        
    - name: Configure Environment
      shell: bash
      env:
        APPLICATION: ${{ inputs.application }}  
        VARIABLES: ${{ inputs.variables }}
        SECRETS: ${{ inputs.secrets }}
      run: |
        REGION_VARIABLE=$(echo ${{ format('{0}_AWS_REGION', env.AWS_ENV) }})
        REGION_VALUE=$( echo $VARIABLES | jq -r ".$REGION_VARIABLE" )
        echo "AWS_REGION=$(echo $REGION_VALUE)" >> "$GITHUB_ENV"
        
        ACCESS_KEY_ID_VARIABLE=$(echo ${{ format('{0}_AWS_ACCESS_KEY_ID', env.AWS_ENV) }})
        ACCESS_KEY_ID_VALUE=$( echo $SECRETS | jq -r ".$ACCESS_KEY_ID_VARIABLE" )
        echo "AWS_ACCESS_KEY_ID=$(echo $ACCESS_KEY_ID_VALUE)" >> "$GITHUB_ENV"

        SECRET_ACCESS_KEY_VARIABLE=$(echo ${{ format('{0}_AWS_SECRET_ACCESS_KEY', env.AWS_ENV) }})
        SECRET_ACCESS_KEY_VALUE=$( echo $SECRETS | jq -r ".$SECRET_ACCESS_KEY_VARIABLE" )
        echo "AWS_SECRET_ACCESS_KEY=$(echo $SECRET_ACCESS_KEY_VALUE)" >> "$GITHUB_ENV"        

        NAMESPACE_VARIABLE=$(echo ${{ format('{0}_{1}_NAMESPACE', env.AWS_ENV, env.APPLICATION_NAME) }})
        NAMESPACE_VALUE=$( echo $VARIABLES | jq -r ".$NAMESPACE_VARIABLE" )
        echo "NAMESPACE=$(echo $NAMESPACE_VALUE)" >> "$GITHUB_ENV" 

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}        
        

